### PR TITLE
Update plotting of RIXS maps

### PR DESCRIPTION
**Pull request by JohanSchott**
- Use imshow instead of contourf when plot RIXS maps.
- Show RIXS intensity values on the colorbar
- Show smaller intensities
-  Updated checked-in RIXS .png figures (using the new plot code)

New RIXS map on the left, old RIXS map on the right:

Screenshot 2024-06-24 at 23 22 49

### CODE REVIEW

**Comment by JohanSchott** [comment]
Plot generated with: `python impurityModel/plotScripts/plotSpectra.py impurityModel/test/referenceOutput/Ni_NiO_50bath/spectra.h5`

**Comment by JohanSchott** [comment]
Plan to merge in 2 days, unless someone has objections/feedback.

**Review by johanjoensson — APPROVED** [review]
This looks good! Good that you removed the pylab dependence!

**Comment by JohanSchott** [comment]
Thanks for the review @johanjoensson !

**Pull request merged**
